### ISSUE TITLE
Kite plugin for pycharm does not show quick documentation and popular patterns.

### ISSUE THREAD

**Issue by nombreinvicto** [kiteco/plugins#109]
Hello,

I am using Pycharm 2018.2.4 on Windows 10.
Kite version: 1.2018.1004.0

The quick documentation pop up for identifiers are not showing the Kite enhanced documentation (that includes function signature, parameters and popular patterns). On the invocation of view quick documentation, no documentation is popping up. 

The IDE is configured so that quick documentation is enabled, so no problem on that side.

**Comment by dhung09** [comment]
Hi @nombreinvicto 

Thanks for your inquiry into this matter. This decision wasn't made lightly so I wanted to provide an in-depth explanation for the product change.

TL;DR - We made the tough decision to discontinue support for documentation inside the editor so that we could focus our efforts on providing the very best Python autocompletions.

As you might know, Kite integrates with 5 different editors. Getting any feature right in a single editor is hard enough, and getting it right in 5 editors is at least 5 times as hard. Given our small team size, we needed to figure out how to utilize our time more appropriately and when we thought about which features would create the most value for our users going forward, it became clear that developing smarter and more context-aware autocompletions would be much more transformative in the long run than maintaining documentation in the editor. We're currently investing a lot of resources into improving our static analysis and machine learning models, and we're very excited at the prospect of shipping more advanced autocompletions for our users.

In the meantime, documentation will still be available in the Copilot and in our Webdocs. While we've also poured a lot of time and effort into these 2 products, we realize that they may not be perfect replacements and we sincerely apologize for the inconvenience. However, we remain committed to our mission of building tools to help you code more efficiently and we're confident our increased investment in AI-powered autocompletions will prove to be useful to you in the coming months.

**Comment by nombreinvicto** [comment]
@dhung09 
Thanks for the feedback!
Kite is awesome and I hope it comes with more awesome features in the future. In the meantime, it would be great if the github documentations were up to date. They still reflect some older features which could be misleading.

**Comment by dhung09** [comment]
Thank you for the support! We're working hard to improve all of our plugins including UI/UX, new features and of course documentation. 🙂 Stay tuned!
