### ISSUE TITLE
Emacs support.

### ISSUE THREAD

**Issue by nasyxx** [kiteco/plugins#125]
Hi, it seems that you have removed emacs support.  Will you support it again?

**Comment by billywade** [comment]
Seconded. What would it take to get Emacs support back, or to at least get the repository back so it can be forked and community maintained?

**Comment by vxe** [comment]
what was the rationale behind removing it in the first place?

**Comment by treymerkley** [comment]
poking back through earlier issues and blog posts, it looks like the reasoning is that the Emacs userbase for their app was too low to justify supporting it further, so they figured they'd take it down. Of course, that's usually counterintuitive to the approach generally taken by free software, to provide the source with the understanding that there will be no official support and that it's officially a community problem.

**Comment by alexmv** [comment]
It looks like documentation for the Emacs plugin [got re-added recently](https://github.com/kiteco/plugins/commit/f9938a8354b887eed2240640420a30f9195bce3c#diff-12535011a437ca8fde22ad1e9a040ad7), probably accidentally?

**Comment by its-dhung** [comment]
We unfortunately are not planning on reintroducing Emacs support in the near future.

**Comment by vxe** [comment]
why don’t you release the original source and let the community maintain it?

**Comment by its-dhung** [comment]
There's no objection to making the original Emacs plugin source public. The issue is that Kite's API has changed drastically since the Emacs plugin was released, so the code wouldn't even work. 

That said, you can check out how our other plugins communicate with Kite if you want to build one on your own. For example, you can emulate what the [Sublime plugin](https://github.com/kiteco/KiteSublime) does.

Alternatively, Kite should be shipping an LSP backend in the near future, so you could also use a LSP client when that happens.

**Comment by treymerkley** [comment]
We do already get pretty decent [LSP support](https://github.com/emacs-lsp/lsp-mode) that should integrate well enough with any languages you decide to write more for. 

Either way, I really appreciate you coming in and explaining it, and thank you for the base software, even if it isn't feasible to maintain a plug-in for our editor specifically.
