### ISSUE TITLE
how to use kite for atom

### ISSUE THREAD

**Issue by aheadlcx** [kiteco/plugins#16]
I have put the plugin for atom under user/.atom/packages.After restart atom, I can not find how to make this plugin work.

**Comment by Rillist** [comment]
yes I just manually installed this for Atom editor as well(not on apm yet?!), and I don't know how to use it either.

Saw a bunch of posts about it recently, seems cool. Wish I could use it. :D

**Comment by alexflint** [comment]
Hey guys, thanks for giving it a whirl. I'm afraid that in order to use Kite you'll need an invite to the beta program (we're trying to scale it up as quickly as possible - really!). Did you already sign up at www.kite.com? If you shoot me a message at alex@kite.com then I'll check where you are on the invite queue.

**Comment by irliao** [comment]
@alexflint messaged!

**Comment by laubosslink** [comment]
Seems a good product, so bad that there is no sample installation to use it easily with atom...

**Comment by adamsmith** [comment]
Hi all, just to close the loop on this thread, you can install Kite for Atom by going to kite.com and downloading Kite there.  Cheers!
