### ISSUE TITLE
vim

### ISSUE THREAD

**Issue by jacquelineCelia** [kiteco/plugins#5]
@tarakju 
### Known issues
- [ ] No`focus` events
- [ ] Diff suggestions (highlight, apply) may not work if the relevant file isn't the file in focus.
- [ ] .py files with unicode characters (e.g. in string literals) won't work, in particular passive search for locations after such literals.
- [ ] Kite fails if UDP port 46625 isn't available for Kite to listen on. One common way this could happen: if multiple "Users" on the machine are running Kite.
- [ ] `error` actions should probably have their own json structure, since they don't include suggestions, and thus should put the error contents in a field instead of in `text` with an extra layer of json encoding.

**Comment by jiangxincode** [comment]
If you want use this plugin with vundle, Please go to jiangxincode/vim-kite. It will update everyday asyn with [](https://github.com/kiteco/plugins)

**Comment by trusktr** [comment]
Supporting NeoVim might be nice (especially with it's async features so that Kite won't block NeoVim's UI like it could with Vim).

**Comment by micku** [comment]
@jiangxincode do you have a plan to update your mirror to the latest version?  
If not, I will create a new one, I just do not want to create another useful-only-for-me repo :)

**Comment by jiangxincode** [comment]
yes， but  i am on holidays, i will back on 10.8来自我的华为手机-------- 原始邮件 --------主题：Re: [kiteco/plugins] vim (#5)发件人：Michele Gargiulo 收件人：kiteco/plugins 抄送：Aloys ,Mention @jiangxincode do you have a plan to update your mirror to the latest version?
If not, I will create a new one, I just do not want to create another useful-only-for-me repo :)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kiteco/plugins","title":"kiteco/plugins","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kiteco/plugins"}},"updates":{"snippets":[{"icon":"PERSON","message":"@micku in #5: @jiangxincode do you have a plan to update your mirror to the latest version?  \r\nIf not, I will create a new one, I just do not want to create another useful-only-for-me repo :)"}],"action":{"name":"View Issue","url":"https://github.com/kiteco/plugins/issues/5#issuecomment-251067874"}}}

**Comment by adamsmith** [comment]
Hi all, neovim and vim now have fancy new, full-featured plugins  : )

**Comment by fdelacruz** [comment]
is vim still supported??

**Comment by jansorg** [comment]
@fdelacruz vim is fully supported. Is there anything not working as expected for you?

**Comment by fdelacruz** [comment]
@jansorg I get the following errors:
```
remote: Repository not found.
fatal: repository 'https://github.com/kiteco/vim-plugin.git/' not found
```
Trying to clone to repo..
```
$ git clone https://github.com/kiteco/vim-plugin.git ~/.config/nvim/pack/kite/start/kite/
```
