### ISSUE TITLE
Sublime Text

### ISSUE THREAD

**Issue by jacquelineCelia** [kiteco/plugins#6]
@tarakju 
### Known issues
- [ ] Same file open multiple times, with different contents in each, may cause issues.
- [ ] Diff suggestions (highlight, apply) may not work if the relevant file isn't the file in focus.
- [ ] .py files with unicode characters (e.g. in string literals) won't work, in particular passive search for locations after such literals.
- [ ] Kite fails if UDP port 46625 isn't available for Kite to listen on. One common way this could happen: if multiple "Users" on the machine are running Kite.
- [ ] `error` actions should probably have their own json structure, since they don't include suggestions, and thus should put the error contents in a field instead of in `text` with an extra layer of json encoding.

**Comment by pirate** [comment]
Can we also add the plugin to https://packagecontrol.io/ for easier installs?

**Comment by alexflint** [comment]
@pirate the plugin won't work until you have a kite account, and we're still in the early stages of sending out invites, so I think we should wait until anybody can just download the kite client before putting this on packagecontrol.

**Comment by pirate** [comment]
@alexflint sounds great 👍, just wanted to make sure it was on the roadmap.

**Comment by afrieder** [comment]
It would be nice if Kite could use the syntax of a file to determine the language, instead of looking at the file extension. For example, if I open a new file and set the syntax to Python, I get "Kite can't automatically show you results for the current file because it has not yet been saved with a supported file extension", even though enough information is there for Kite to tell.
