### ISSUE TITLE
emacs plugin causes a stuttery cursor in the terminal

### ISSUE THREAD

**Issue by varenc** [kiteco/plugins#72]
After installing the Kite emacs plugin emacs's cursor movement has become very stuttery.  Lots of starts and stops making moving around with my cursor painful.  Even after quitting Kite the performance degradation persists.  Uninstalling the kite plugin fixes the issue.

Here's a little video of the issue: https://www.dropbox.com/s/qqv0d9xleub974r/sademacs.mov

I assume some work the plugin does is slowing down emacs.  If I had to guess, this might only be a problem for people using emacs in the terminal like me, instead of the GUI?  The GUI might have a separate thread for UI interactions.

this is emacs version `25.1.1`

p.s. as a side note, I've never had an easier time install and uninstalling an emacs extension.  Kudos!

**Comment by adamsmith** [comment]
hi Chris, great to hear from you!!

yeah, sadly our emacs plugin is a bit behind the curve because it has the fewest users.  it still uses an events API to the kite engine that has been replaced for almost the last year!

(back-story: we used to use UDP to send events to the kite engine but now we use HTTP.  emacs didn't have the ability to send UDP packets so we have emacs fork a process called `udswrite` which sends the UDP packet.)

a couple of quick other notes:

1) if you had an old install of Kite, make sure Accessibility permissions are turned off for Kite.  we decided to disable our bash command responses recently for the time being because of performance issues with listening to Accessibility events from Terminal.app.

2) we have some pretty awesome integrations coming for the mainstream editors: unfortunately not emacs but PyCharm is getting some pretty awesome stuff in the next 1-3 weeks!

**Comment by varenc** [comment]
sadly removing accessibility permission for Kite didn't fix this for me. (and I installed it 9 days ago, so must be a recent version that still adds permissions?)

That said focusing on PyCharm sounds like a great call and that's what I use most of the time.  If you can fix the compatibility issue with older PyCharm versions I'll use it there.

**Comment by its-dhung** [comment]
emacs support has been discontinued, so closing.
